Create Dockerfile
ALTF4Team/altf4-backend pull request #4
Opened 2023-04-17 12:08 UTC by sharat789

2023-04-17 12:09 UTC, bridzius approved these changes

2023-04-17 14:33 UTC, NeHerkus requested changes

2023-04-17 14:33 UTC, NeHerkus commented on Dockerfile
> +CMD ["java", "-jar", "build/libs/message.jar"]
You can update this to have the actual jar name.

2023-04-19 11:20 UTC, sharat789 reviewed
Changed it

2023-04-19 12:02 UTC, NeHerkus approved these changes

2023-04-19 12:26 UTC, merged